name: retail_revenue_analytics
version: 1.0.0
config-version: 2

profile: retail_revenue_analytics

model-paths:
  - models
test-paths:
  - tests

models:
  retail_revenue_analytics:
    staging:
      +materialized: ephemeral
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
