name: job_market_analytics
version: 1.0.0
config-version: 2

profile: job_market_analytics

model-paths:
  - models
macro-paths:
  - macros
test-paths:
  - tests

models:
  job_market_analytics:
    staging:
      +materialized: ephemeral
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
