name: job_market_analytics
version: 1.0.0
config-version: 2

profile: job_market_analytics

model-paths:
  - models

models:
  job_market_analytics:
    bronze:
      +materialized: view
    silver:
      +materialized: view
    gold:
      +materialized: table
